### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Emojees**
makes small changes to the readme file of the source code

### CODE REVIEW

**Review by Kuefo — APPROVED** [review]
looks good, and thank you for contributing!

**Comment by V3ntus** [comment]
looks like shit bro

**Comment by Emojees** [comment]
> looks like shit bro

don't say those kinds of things about your mother lil bro

**Comment by V3ntus** [comment]
you forgot to log out of your alt account kiddo

**Comment by Emojees** [comment]
> you forgot to log out of your alt account kiddo

what are you on about? i barely even know this guy i just like his projects lol

**Comment by V3ntus** [comment]
says the loser @Emojees

**Comment by Emojees** [comment]
> you forgot to log out of your alt account kiddo

oh how ironic that is coming from the guy who's going out of his way to hate on other people's projects for no reason

**Comment by V3ntus** [comment]
calling this a "project" is a long shot, this concoction of words and characters you have here is poop from a butt

**Pull request merged**
